config/routes.rb
Rails.application.routes.draw do
  resources :appointments

  get 'welcome/index'
  get 'welcome/patient'
  get 'welcome/physician'
  get 'welcome/employee'
  get 'welcome/appointment'
  get 'welcome/insurance'
  get 'welcome/invoice'
  get 'welcome/diagnostic'

  resources :invoices

  resources :diagnostics

  resources :insurances

  resources :employees

  resources :physicians

  resources :patients

  root to: 'welcome#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :physician
  belongs_to :patient
  belongs_to :diagnostic
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  respond_to :html
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show

    @appointment = Appointment.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = AppointmentPdf.new(@appointment)

        send_data pdf.render, filename: "appointment_#{@appointment_id}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  def send_date(i, options)
    # code here
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:physician_id, :patient_id, :date, :reason, :notes, :diagnostic_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :physician_id %><br>
    <%= f.collection_select :physician_id, Physician.all, :id, :first_name, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.collection_select :patient_id, Patient.all, :id, :first_name, :prompt => true %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date, :id => 'datetimepicker' %>
  </div>
  <div class="field">
    <%= f.label :reason %><br>
    <%= f.text_area :reason %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :diagnostic_id %><br>
    <%= f.collection_select :diagnostic_id, Diagnostic.all, :id, :description, :prompt => true %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<div class="media">
  <div class="media-body">
    <table class="table table-hover">
  <thead>
    <tr>
      <th>Physician</th>
      <th>Patient</th>
      <th>Date</th>
      <th>Reason</th>
      <th>Notes</th>
      <th>Diagnostic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.physician.first_name %>
          <%= appointment.physician.last_name %></td>
        <td><%= appointment.patient.first_name %>
          <%= appointment.patient.last_name %></td>
        <td><%= appointment.date %></td>
        <td><%= appointment.reason %></td>
        <td><%= appointment.notes %></td>
        <td><%= appointment.diagnostic.code %></td>
        <td><%= link_to 'Show', appointment, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to "Printable Receipt (PDF)", appointment_path(appointment, format: "pdf") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
  </div>
<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Physician:</strong>
  <%= @appointment.physician.first_name %>
  <%= @appointment.physician.last_name %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient.first_name %>
  <%= @appointment.patient.last_name %>

</p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @appointment.reason %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @appointment.notes %>
</p>

<p>
  <strong>Diagnostic:</strong>
  <%= @appointment.diagnostic.description %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>